### ISSUE TITLE
Sparsity may still cause issue for constraint duals

### ISSUE THREAD

**Issue by ssadat** [exanauts/ActiveSetMethods#42]

**Comment by kibaekkim** [comment]
I believe this has been resolved by the commits addressing #32. @ssadat You can reopen this if you observe any issue.

**Comment by ssadat** [comment]
@kibaekkim I think we can still have issues. I will try it locally with a couple of examples.

**Comment by ssadat** [comment]
There is a potential to take advantage of sparsity to reduced the number of constraints of the LP subproblem. Initially, I thought I have implemented it and it might cause issues with the current implementation of retrieving the duals of constraints. Now I see that the advantage of sparsity hasn't been taken to full potential, though it is not causing any issues, I believe we should take advantage of sparsity which will be useful for large cases to reduce the computation time.

**Comment by kibaekkim** [comment]
@ssadat OK. Can you describe more about your idea with technical details? If you want, you can use our Overleaf doc. Where does the sparsity come from? How would you use it?

**Comment by kibaekkim** [comment]
Reading the overleaf doc, I understand the idea. 
Just to note, my expectation is the performance gain may be marginal because most (if not all) LP solvers do presolve.
If you decide to proceed this, please make sure that the indices for multipliers are not messed up.

**Comment by kibaekkim** [comment]
My quick comment is that what you may have done (without looking at your code) would change the dimension of the dual variables. But, as we discussed before, I think this must be something addressed in LP solver. So, the performance gain would be very marginal, if any.

**Comment by ssadat** [comment]
@kibaekkim I had taken care of that and I don't think there is any dimension conflict. The improvement would likely be marginal as you said. That's why I will keep it for later and won't invest any more time on it right now.
